ekf_odom:
  ros__parameters:
    # Frames
    base_link_frame: base_link
    odom_frame: odom
    world_frame: odom
    map_frame: map
    publish_tf: true
    two_d_mode: true

    # Timing
    frequency: 50.0                # publish /odometry/filtered at 50 Hz
    sensor_timeout: 0.12           # ok for 50 Hz odom + 100–200 Hz IMU
    transform_timeout: 0.02
    print_diagnostics: true

    # =======================
    #   INPUT 0: /odom
    # =======================
    odom0: /odom
    odom0_queue_size: 10
    odom0_differential: false      # your MCU already outputs absolute (x,y,theta)
    odom0_relative: false
    # state vector order (15):
    # x y z  roll pitch yaw  vx vy vz  vroll vpitch vyaw  ax ay az
    odom0_config: [ true, true, false,
                    false, false, true,
                    true,  true,  false,
                    false, false, true,
                    false, false, false ]

    # Let EKF trust odom more on pose than on twist at first; you can tune later:
    odom0_pose_rejection_threshold: 5.0      # meters/radians
    odom0_twist_rejection_threshold: 5.0     # m/s or rad/s

    # =======================
    #   INPUT 1: /imu/data
    # =======================
    imu0: /imu/data
    imu0_queue_size: 25
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true   # you send raw accel with gravity
    # fuse gyro (rates) + linear accel; no orientation provided
    imu0_config: [ false, false, false,
                   false, false, false,
                   false, false, false,
                   true,  true,  true,
                   true,  true,  true ]

    # =======================
    #   NOISE (tune later)
    # =======================
    process_noise_covariance: [ 0.10, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0.10, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0.01, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0.01, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0.01, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0.05, 0,    0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0.50, 0,    0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0.50, 0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0.01, 0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0.05, 0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.05, 0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0.10, 0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0,  0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0,  0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0 ]

    initial_estimate_covariance:  [ 1e-3, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    1e-3, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    1e-1, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    1e-1, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    1e-1, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    1e-2, 0,    0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    5e-2, 0,    0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    5e-2, 0,    0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    1e-2, 0,    0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    5e-3, 0,    0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    5e-3, 0,    0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    5e-2, 0,    0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0,  0,    0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0,  0,
                                    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0 ]
