# Frames & common
amcl:  # not used while mapping, but keep frames consistent if later needed
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: /scan

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml"
    plugin_lib_names: ["nav2_bt_navigator/BtNavigator"]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.30
      max_linear_accel: 0.6
      max_angular_vel: 1.5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.30
      max_lookahead_dist: 0.90
      use_velocity_scaled_lookahead_dist: true
      rotate_to_heading_angular_vel: 1.0
      allow_reversing: false
      use_rotate_to_heading: true

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.10

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["Simple"]
    Simple:
      plugin: "nav2_smoother/SimpleSmoother"
      tolerance: 1.0e-10

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    track_unknown_space: true
    rolling_window: false
    robot_radius: 0.185
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d/ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        obstacle_range: 8.0
        raytrace_range: 10.0
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      inflation_radius: 0.55
      cost_scaling_factor: 3.0

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    robot_radius: 0.185
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d/ObstacleLayer"
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        obstacle_range: 8.0
        raytrace_range: 10.0
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      inflation_radius: 0.50
      cost_scaling_factor: 3.0

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ["controller_server",
                 "planner_server",
                 "bt_navigator",
                 "smoother_server",
                 "behavior_server",
                 "waypoint_follower"]
