# Generated by Django 6.0.2 on 2026-02-21 07:30

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '001_enable_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('url', 'URL'), ('pdf', 'PDF')], max_length=8)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=255)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='kb.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source'], name='kb_chunk_source__a086f1_idx')],
                'unique_together': {('source', 'chunk_index')},
            },
        ),
    ]
