# Generated by Django 6.0.2 on 2026-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='ready', max_length=16),
        ),
    ]
