# Generated by Django 6.0.2 on 2026-03-23 18:50

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_source_last_error_source_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
