# Generated by Django 6.0.2 on 2026-04-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_chunk_search_text_chunk_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
